# Auto-generated from species0717.csv
# Do not edit manually.

SPECIES = {'grona_triflora_(l.)_h.ohashi_&_k.ohashi': {'number': '1',
                                             'code': '1_GT',
                                             'species_name': 'Grona triflora (L.) H.Ohashi & '
                                                             'K.Ohashi',
                                             'common_name_zh': '蠅翼草 / 三點金',
                                             'common_name_en': 'creeping tick trefoil',
                                             'subfamily': 'Faboideae',
                                             'tribe_name': 'Desmodieae'},
 'grona_heterophylla': {'number': '2',
                        'code': '2_GH',
                        'species_name': 'Grona heterophylla',
                        'common_name_zh': '異葉山螞蝗',
                        'common_name_en': 'variable-leaf tick trefoil',
                        'subfamily': 'Faboideae',
                        'tribe_name': 'Desmodieae'},
 'medicago_lupulina': {'number': '3',
                       'code': '3_ML',
                       'species_name': 'Medicago lupulina',
                       'common_name_zh': '天藍苜蓿',
                       'common_name_en': 'black medick',
                       'subfamily': 'Faboideae',
                       'tribe_name': 'Trifolieae'},
 'mimosa_pudica': {'number': '4',
                   'code': '4_MP',
                   'species_name': 'Mimosa pudica',
                   'common_name_zh': '含羞草',
                   'common_name_en': 'sensitive plant',
                   'subfamily': 'Mimosoideae',
                   'tribe_name': 'Mimoseae'},
 'melilotus_suaveolens': {'number': '5',
                          'code': '5_MS',
                          'species_name': 'Melilotus suaveolens',
                          'common_name_zh': '草木樨',
                          'common_name_en': 'sweetclover',
                          'subfamily': 'Faboideae',
                          'tribe_name': 'Trifolieae'},
 'alysicarpus_vaginalis': {'number': '6',
                           'code': '6_AV',
                           'species_name': 'Alysicarpus vaginalis',
                           'common_name_zh': '煉莢豆',
                           'common_name_en': 'alyce clover / white moneywort',
                           'subfamily': 'Faboideae',
                           'tribe_name': 'Desmodieae'},
 'kummerowia_striata': {'number': '7',
                        'code': '7_KS',
                        'species_name': 'Kummerowia striata',
                        'common_name_zh': '雞眼草',
                        'common_name_en': 'Japanese clover',
                        'subfamily': 'Faboideae',
                        'tribe_name': 'Desmodieae'},
 'arachis_pintoi': {'number': '8',
                    'code': '8_AP',
                    'species_name': 'Arachis pintoi',
                    'common_name_zh': '蔓花生',
                    'common_name_en': 'wild peanut',
                    'subfamily': 'Faboideae',
                    'tribe_name': 'Dalbergieae'},
 'trifolium_repens': {'number': '9',
                      'code': '9_TR',
                      'species_name': 'Trifolium repens',
                      'common_name_zh': '白三葉草 / 菽草',
                      'common_name_en': 'white clover',
                      'subfamily': 'Faboideae',
                      'tribe_name': 'Trifolieae'},
 'grona_heterocarpa_subsp._heterocarpa_(l.)_h.ohashi_&_k.ohashi': {'number': '10',
                                                                   'code': '10_GH',
                                                                   'species_name': 'Grona '
                                                                                   'heterocarpa '
                                                                                   'subsp. '
                                                                                   'heterocarpa '
                                                                                   '(L.) H.Ohashi '
                                                                                   '& K.Ohashi',
                                                                   'common_name_zh': '假地豆',
                                                                   'common_name_en': 'asian '
                                                                                     'ticktrefoil',
                                                                   'subfamily': 'Faboideae',
                                                                   'tribe_name': 'Desmodieae'},
 'indigofera_hendecaphylla_jacq.': {'number': '11',
                                    'code': '11_IH',
                                    'species_name': 'Indigofera hendecaphylla Jacq.',
                                    'common_name_zh': '穗花木藍',
                                    'common_name_en': 'trailing indigo',
                                    'subfamily': 'Faboideae',
                                    'tribe_name': 'Indigofereae'},
 'lespedeza_thunbergii_subsp._formosa_(vogel)_h.ohashi': {'number': '12',
                                                          'code': '12_LT',
                                                          'species_name': 'Lespedeza thunbergii '
                                                                          'subsp. formosa (Vogel) '
                                                                          'H.Ohashi',
                                                          'common_name_zh': '胡枝子',
                                                          'common_name_en': 'bush clovers',
                                                          'subfamily': 'Faboideae',
                                                          'tribe_name': 'Desmodieae'},
 'chamaecrista_nictitans': {'number': '13',
                            'code': '13_CN',
                            'species_name': 'Chamaecrista nictitans',
                            'common_name_zh': '假山扁豆',
                            'common_name_en': 'sensitive pea',
                            'subfamily': 'Caesalpinioideae',
                            'tribe_name': 'Cassieae'},
 'crotalaria_juncea': {'number': '14',
                       'code': '14_CJ',
                       'species_name': 'Crotalaria juncea',
                       'common_name_zh': '太陽麻 / 菽麻',
                       'common_name_en': 'sunn hemp',
                       'subfamily': 'Faboideae',
                       'tribe_name': 'Crotalarieae'},
 'christia_obcordata': {'number': '15',
                        'code': '15_CO',
                        'species_name': 'Christia obcordata',
                        'common_name_zh': '鋪地蝙蝠草',
                        'common_name_en': 'swallow tail / butterfly plant',
                        'subfamily': 'Faboideae',
                        'tribe_name': 'Desmodieae'},
 'leucaena_leucocephala': {'number': '16',
                           'code': '16_LL',
                           'species_name': 'Leucaena leucocephala',
                           'common_name_zh': '銀合歡',
                           'common_name_en': 'white leadtree',
                           'subfamily': 'Mimosoideae',
                           'tribe_name': 'Mimoseae'},
 'indigofera_spicata': {'number': '17',
                        'code': '17_IS',
                        'species_name': 'Indigofera spicata',
                        'common_name_zh': '倒卵葉木藍',
                        'common_name_en': 'creeping Indigo',
                        'subfamily': 'Faboideae',
                        'tribe_name': 'Indigofereae'},
 'n/a': {'number': '18',
         'code': None,
         'species_name': 'N/A',
         'common_name_zh': '疑似一條根',
         'common_name_en': 'N/A',
         'subfamily': 'N/A',
         'tribe_name': 'N/A'},
 'macroptilium_lathyroides': {'number': '19',
                              'code': '19_ML',
                              'species_name': 'Macroptilium lathyroides',
                              'common_name_zh': '寬翼豆',
                              'common_name_en': 'phasey bean',
                              'subfamily': 'Faboideae',
                              'tribe_name': 'Phaseoleae'},
 'sesbania_cannabina': {'number': '20',
                        'code': '20_SC',
                        'species_name': 'Sesbania cannabina',
                        'common_name_zh': '田菁',
                        'common_name_en': 'sesbania Pea',
                        'subfamily': 'Faboideae',
                        'tribe_name': 'Sesbanieae'}}
